import CategoryBar from "@/components/CategoryBar";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Suspense } from "react";

export const metadata = {
  title: "Youtube Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-neutral-950 text-gray-900 dark:text-gray-100">
        <Header />
        <Sidebar />
        <div className="ml-0 md:ml-56 pt-16">
          {" "}
          <Suspense fallback={null}>
            <CategoryBar />
          </Suspense>
          <main className="p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
